name = "Preferences"
uuid = "21216c6a-2e73-6563-6e65-726566657250"
authors = ["Elliot Saba <elliot.saba@juliacomputing.com>", "contributors"]
version = "1.4.3"

[deps]
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Pkg", "SHA", "Test"]

[compat]
julia = "1.0"
